src/Entity/Releve.php
<?php

namespace App\Entity;

use App\Repository\ReleveRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Random\RandomException;

#[ORM\Entity(repositoryClass: ReleveRepository::class)]
class Releve
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'releves')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Lieu $lieu = null;

    #[ORM\Column(length: 17)]
    private ?string $releve_brut = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getReleveBrut(): ?string
    {
        return $this->releve_brut;
    }

    public function setReleveBrut(string $releve_brut): static
    {
        $this->releve_brut = $releve_brut;

        return $this;
    }

    /**
     * @throws RandomException
     */
    public function generateTable(): array
    {
        $matrice = [];
        $releve_brut = array_map('intval', explode('/', $this->getReleveBrut()));
    
        for ($y = 0; $y < 3; $y++) {
            $matrice[$y] = [];
            for ($x = 0; $x < 3; $x++) {
                $matrice[$y][$x] = [];
    
                for ($i = 0; $i < $releve_brut[$y * 3 + $x]; $i++) {
                    $index = random_int(0, 8);
                    while (in_array($index, $matrice[$y][$x])) {
                        $index = random_int(0, 8);
                    }
    
                    $matrice[$y][$x][] = $index;
                }
            }
        }
        return $matrice;
    }    
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Releve;
use App\Form\ReleveType;
use Symfony\Component\HttpFoundation\Request;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]

    public function index(EntityManagerInterface $doctrine, Request $request): Response
    { 
        $releves = $doctrine->getRepository(Releve::class)->findAll();

        $releve = new Releve();
        $form = $this->createForm(ReleveType::class, $releve);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $doctrine->persist($releve);
            $doctrine->flush();

            return $this->redirectToRoute('app_home');
        }

        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'releves' => $releves,
            'form' => $form->createView(),
        ]);
    }
}

        

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Herbiers - Claire Nguyen{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>Relevés</h1>
    
    <div class="tableau">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Lieu</th>
                    <th>Relevé brut</th>
                    <th>Tableau</th>
                    <th>Visualisation</th>
                    <th>Modification</th>
                    <th>Suppression</th>
                </tr>
            </thead>

            <tbody>
                {% for releve in releves %}
                    <tr>
                        <td>{{ releve.date|date('d/m/Y') }}</td>
                        <td>{{ releve.lieu.nom }}</td>
                        <td>{{ releve.releveBrut }}</td>
                        <td>
                            <table class="table table-bordered">
                            {% set c = 0 %}
                            {% for u in 0..2 %}
                                <tr>
                                    {% for i in 0..2 %}
                                        {% if c <= 9 %}
                                            <td>{{ releve.releveBrut|split('/')[c]}}</td>
                                        {% endif %}
                                        {% set c = c + 1 %}
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                            </table>
                        </td>
                        <td>
                            <table class="visualisation">
                                {% set visualisation = releve.generateTable %}
                                {% for r in visualisation %}
                                 <tr>
                                {% for q in r %}
                                <td>
                                    <table class="petitTableau">
                                    {% for i in 0..2 %}
                                    <tr>
                                        {% for u in 0..2 %}
                                        <td {% if (i * 3 + u) in q %}class="herbe"{% endif %}></td>
                                        {% endfor %}
                                    </tr>
                                        {% endfor %}    
                                    </table>
                                </td>
                                {% endfor %}
                            </tr>
                            {% endfor %}
                        </table>
                        </td>
                        <td><a class="btn btn-outline-info" href="{{ path('app_releve_edit', {'id': releve.id}) }}">Modifier</a></td>
                        <td>{{ include('releve/_delete_form.html.twig') }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">Aucun relevé trouvé</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="add-releve">
        <h2>Ajouter un relevé</h2>
        {{ include('releve/_form.html.twig') }}
    </div>

</div>
{% endblock %}